### ISSUE TITLE
Incorrect error checking (negative array read)

### ISSUE THREAD

**Issue by MegaManSec** [samboy/MaraDNS#20]
Hi,

in ParseMaraRc.c in the new_dvar() function:
450    num = dkeyword2num(name);
451    if(dvar[num] != 0 || num < 0 || num > DKEYCOUNT)

The check for "num < 0" should be done before "dvar[num] != 0", as dkeyword2num may return a negative number.

Thanks,

**Comment by Remmy** [comment]
Also, does this not suffer the same problem as issue #19, and should the check be for num >= DKEYCOUNT?

**Comment by MegaManSec** [comment]
Yes, you're right :)
Well, issue #19  should be patched by changing the check to "index > DKEYCOUNT".
This one should be fixed by moving the 'dvar[num] != 0' check to the end, and changing the dkey check to "index > DKEYCOUNT", too.

Thanks

**Comment by samboy** [comment]
The exploit vector requires the attacker to control a mararc file, a file usually only edited by root, and requires whatever memory location two pointers before the beginning of dvar to be precisely zero, which should be unlikely. 

I’ve fixed this, but this isn’t serious enough for me to waste two to three hours making a new MaraDNS release, especially since I just made a release last week.

**Comment by samboy** [comment]
I just checked, and, yes, MaraDNS 1.0.00 from 2002 has this particular bug. Most of the things like this people are finding these days come from the 2001-2002 codebase; I wrote too much code too quickly because there was a hurry to have an open-source DNS server that wasn’t BIND at the time.

**Comment by samboy** [comment]
Another thing: The exploit is actually very limited.  You can’t write to any memory with this bug; you can only force MaraDNS to **read** from a memory location she should not read from.
