### ISSUE TITLE
timeout_seconds isn't always respected

### ISSUE THREAD

**Issue by gthreepw00d** [samboy/MaraDNS#23]
My setup is dnsmasq -> deadwood -> google dns. Basically, deadwood works as AAAA filter.
> bind_address="127.0.0.1"
> dns_port=54
> chroot_dir = "/etc/deadwood"
> upstream_servers = {}
> upstream_servers["."]="8.8.8.8,8.8.4.4"
> recursive_acl = "127.0.0.1/16"
> maxprocs = 50
> handle_overload = 1
> maradns_uid = 99
> maradns_gid = 99
> maximum_cache_elements = 1
> timeout_seconds=3
> reject_aaaa=1

Here is what I'd caught:

> 
> **(1)** 09:08:40.000652 IP 192.168.0.10.41797 > 192.168.0.1.53: 49993+ [1au] A? aac.opennicproject.org. (51)
> **(2)** 09:08:40.000676 IP 192.168.0.10.41797 > 192.168.0.1.53: 49993+ [1au] A? aac.opennicproject.org. (51)
> **(3)** 09:08:40.003320 IP 127.0.0.1.51579 > 127.0.0.1.54: UDP, length 51
> **(4)** 09:08:40.004120 IP x.x.x.x.15928 > 8.8.8.8.53: 4556+ A? aac.opennicproject.org. (40)
> **(5)** 09:08:43.000077 IP 192.168.0.10.41797 > 192.168.0.1.53: 49993+ [1au] A? aac.opennicproject.org. (51)
> **(6)** 09:08:43.000101 IP 192.168.0.10.41797 > 192.168.0.1.53: 49993+ [1au] A? aac.opennicproject.org. (51)
> **(7)** 09:08:43.001453 IP 127.0.0.1.51579 > 127.0.0.1.54: UDP, length 51
> **(8)** 09:08:45.016526 IP 8.8.8.8.53 > x.x.x.x.15928: 4556 ServFail 0/0/0 (40)
> **(9)** 09:08:46.000242 IP 192.168.0.10.41797 > 192.168.0.1.53: 49993+ [1au] A? aac.opennicproject.org. (51)
> **(10)** 09:08:46.000266 IP 192.168.0.10.41797 > 192.168.0.1.53: 49993+ [1au] A? aac.opennicproject.org. (51)
> **(11)** 09:08:46.001575 IP 127.0.0.1.51579 > 127.0.0.1.54: UDP, length 51
> **(12)** 09:08:49.058814 IP x.x.x.x.16023 > 8.8.4.4.53: 22902+ [b2&3=0x180] A? aac.opennicproject.org. (40)

(1) and (2): client asks dnsmasq
(3): dnsmasq asks deadwood
(4): deadwood asks first upstream
(8): upstream answers with servfail
(12): deadwood asks second upstream
But with current config I expect 3 sec between (4) and (12), not 9 sec.
As aside note,  `[b2&3=0x180]` in (12) says that RA is set. Not harmful, but for what?

**Comment by samboy** [comment]
Just so you know, both timeout_seconds and num_retries are tested every time I make a Deadwood release:

https://github.com/samboy/MaraDNS/blob/master/deadwood-github/sqa/dwood2rc_n_timeout_seconds/do.test

https://github.com/samboy/MaraDNS/blob/master/deadwood-github/sqa/dwood2rc_n_num_retries/do.test

Both tests pass every time I make a Deadwood release, so my tentative reply is “works for me.” 

Hopefully I will get time to look at this over the next couple of months; since this doesn’t have security consequences, and since I’m not getting paid, I’m not going to make this a priority.

**Comment by samboy** [comment]
Even though I just closed two other bugs, I’m keeping this on the back burner. I will need to come up with some testing code to try and replicate this bug. That’s non-trivial work, so I may or may not get around to it...eventually. 

I have tried to find someone to step up to the plate as a maintainer for MaraDNS or to start a MaraDNS-ng fork; no one wants to do all that work for free. Welcome to the world of open source economics: The code is free, but there is no guarantee of support, since there is no money on the table compelling one to support the program.

**Comment by samboy** [comment]
Closing. It works for me — I do run automated tests making sure that variable reasonably changes Deadwood‘s behavior. Making a test case to see if there really is something going on is too much trouble for something that is not a security bug.

**Comment by samboy** [comment]
Considering that they just opened up multiple CVEs for Dnsmasq, including the critical CVE-2017-14493 issue, this could very well be a Dnsmasq issue. The other six are: CVE-2017-14491, CVE-2017-14492, CVE-2017-14494, CVE-2017-14495, CVE-2017-14496, and CVE-2017-13704
