### ISSUE TITLE
[bug] deadwood 3.2.11 - MX records not being resolved

### ISSUE THREAD

**Issue by n8v8R** [samboy/MaraDNS#43]
unbuntu bionic
kernel 4.17.8
deadwood 3.2.11 (export FLAGS='-O3 -DIPV6')

---
deadwood is working well except it appears not resolving MX records. Every MX query is timing out.

Keeping watch on logs of the upstream resolver it is apparent that any MX query made by deadwood is not reaching the upstream resolver. There is no issue with the upstream resolver on MX records however since clients with dnsmaq or systemd-resolved having no trouble in resolving MX records

**Comment by n8v8R** [comment]
Turned out to be a parsing issue of reolv.conf.

**Comment by n8v8R** [comment]
the log is stating 

> /usr/local/bin/Deadwood[88]: Attempt to get MX record (possible spam z

looked up the documentation and inet but could not find refence...?

Any other DNS records are fetched with no issue

**Comment by samboy** [comment]
The reason why `MX` resolution is disabled by default is because Deadwood is not designed to perform DNS resolution for mail hubs.  I have not tested this use case with Deadwood, and Deadwood does not supply `A` records when asked for `MX` records.

Hence, one needs to dig through the manual to figure out how to enable resolution of `MX` records with  Deadwood. My official solution is this: If you want a DNS server to resolve `MX` records, use once which has been tested with this use case (Some DNS servers to try out: https://www.knot-resolver.cz/ https://nlnetlabs.nl/projects/unbound/about/ etc.

**Comment by samboy** [comment]
Seven days since last comment. Locking to prevent spam.
