### ISSUE TITLE
[Deadwood 3.2.12] duende not building

### ISSUE THREAD

**Issue by n8v8R** [samboy/MaraDNS#45]
3.2.11 did not exhibit this issue:

> cc -O3 -o duende duende.c
> duende.c: In function ‘main’:
> duende.c:163:9: warning: implicit declaration of function ‘strncasecmp’ [-Wimplicit-function-declaration]
>      if(!strncasecmp(argv[1],"--pid=",6)) {

**Comment by samboy** [comment]
The files are identical:

```
$ sha256sum deadwood-3.2.11/tools/duende.c 
c1d19e4fb723cd8a1021d89c198d893384f9250d4ceef3b8a9f37b221ee88299  deadwood-3.2.11/tools/duende.c
$ sha256sum deadwood-3.2.12/tools/duende.c 
c1d19e4fb723cd8a1021d89c198d893384f9250d4ceef3b8a9f37b221ee88299  deadwood-3.2.12/tools/duende.c
```

The issue is clang specific, and it’s only a warning; the program still compiles:

```
$ gcc -O3 -o duende duende.c
$ rm duende
$ clang -O3 -o duende duende.c
duende.c:163:9: warning: implicitly declaring library function 'strncasecmp'
      with type 'int (const char *, const char *, unsigned long)'
    if(!strncasecmp(argv[1],"--pid=",6)) {
        ^
duende.c:163:9: note: please include the header <strings.h> or explicitly
      provide a declaration for 'strncasecmp'
1 warning generated.
$ ls -l duende
-rwxrwxr-x. 1 set set 14008 Sep  2 07:40 duende
```

If it bothers you, this shell (Bash, as people call it these days, but old school UNIX greybeards try to avoid “Bashisms” in their scripts) script will make a duende-clang.c that solves the issue:

```bash
#!/bin/sh
echo '#include <strings.h>' > duende-clang.c 
cat duende.c >> duende-clang.c 
clang -O3 -o duende duende-clang.c
```

The point being, we add the line `#include <strings.h>` to the beginning of the file `duende.c`.

I’m not going to make this change to the MaraDNS code base, because I only fix compile errors, *not* compile warnings. There is a small but distinct chance this will cause the code to not compile for someone using an obscure version of BSD, QNX or what not, and I do not want to introduce that risk.
