### ISSUE TITLE
maradns-zoneserver fails to start under systemd unless started as a subprocess

### ISSUE THREAD

**Issue by pillarsdotnet** [samboy/MaraDNS#83]
As I noted in your [support forum](https://forum.samiam.org/forum/topic/systemd-unit-for-zoneserver/), starting zoneserver under systemd fails unless I run it as a child process.

This fails:

`ExecStart=usr/sbin/zoneserver -f /etc/maradns/mararc`

But this succeeds:

`ExecStart=/usr/bin/strace -f /usr/sbin/zoneserver -f /etc/maradns/mararc`

This also succeeds:

`ExecStart=/bin/sh -c '/usr/sbin/zoneserver -f /etc/maradns/mararc'`

Here is some example `journalctl` output for the failing case:

```
Sep 08 00:36:33 foundry.bobvincent.com zoneserver[123151]: Operation not permitted
Sep 08 00:36:33 foundry.bobvincent.com systemd[1]: maradns-zoneserver.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Sep 08 00:36:33 foundry.bobvincent.com systemd[1]: maradns-zoneserver.service: Failed with result 'exit-code'.
```

Here is the output when running under `/bin/sh`:

```
Sep 08 14:00:35 foundry.bobvincent.com systemd[1]: Started MaraDNS Zoneserver handles DNS zone transfers and any TCP DNS queries.
Sep 08 14:14:41 foundry.bobvincent.com dash[136306]: Log: Root directory changed
Sep 08 14:14:41 foundry.bobvincent.com dash[136306]: Log: Socket opened on TCP port 53
Sep 08 14:14:41 foundry.bobvincent.com dash[136306]: Log: Root privileges dropped
```

Setting `verbose_level = 4 ` in `/etc/maradns/mararc` did not affect the output during startup or failure.

**Comment by samboy** [comment]
Works for me. On bare metal CentOS 8:

```
MaraDNS/tcp# ./zoneserver -f ../doc/en/examples/example_mararc
Log: Root directory changed
Log: Socket opened on TCP port 53
Log: Root privileges dropped
```

The correct way to run `zoneserver` is with the Duende tool:

```
duende zoneserver -f ../doc/en/examples/example_mararc
```

Systemd is not a supported way of running MaraDNS. The script to start MaraDNS is here:

https://github.com/samboy/MaraDNS/blob/master/build/zoneserver.startup

Closing as `WorksForMe` but I will continue this conversation on the support forum.

**Comment by pillarsdotnet** [comment]
> Works for me. On bare metal CentOS 8:
> 
> ```
> MaraDNS/tcp# ./zoneserver -f ../doc/en/examples/example_mararc
> Log: Root directory changed
> Log: Socket opened on TCP port 53
> Log: Root privileges dropped
> ```
> 
> The correct way to run `zoneserver` is with the Duende tool:
> 
> ```
> duende zoneserver -f ../doc/en/examples/example_mararc
> ```
> 
> Systemd is not a supported way of running MaraDNS. The script to start MaraDNS is here:
> 
> https://github.com/samboy/MaraDNS/blob/master/build/zoneserver.startup
> 
> Closing as `WorksForMe` but I will continue this conversation on the support forum.

Oh, it works for me too, from the command-line. Just doesn't work when started from systemd using the ExecStart line above.

Thanks for the pointer to the `duende` tool; I'll read up on it and try to adjust my service file accordingly.

**Comment by samboy** [comment]
If the `duende` daemonizer can make `zoneserver` a background service but `systemd` is unable to do this, this sounds like a bug with `systemd`, not `zoneserver`. 

As an aside, I am pleased to see `systemd` can make a foreground process a daemon running in the background; for years it was considered the responsibility for each service to daemonize itself (i.e. run fork(), then put the child process in its own process group, and then have the foreground process exit once the child process was running. Bonus points when the parent process reported the process ID of the now-darmonized program). I frequently got complaints on the old MaraDNS mailing list that it did not have built-in daemonization, which is why I finally wrote `duende`.

**Comment by samboy** [comment]
Let’s continue this conversation over at https://forum.samiam.org/forum/topic/systemd-unit-for-zoneserver/

Systemd officially is not a supported daemonizer for MaraDNS services, so it’s more a conversation about whether it’s worth it to update MaraDNS to use systemd instead of the old school SysV init scripts it currently uses.
