### ISSUE TITLE
An entry cannot be changed?

### ISSUE THREAD

**Issue by ohaya** [samboy/MaraDNS#98]
Hi,

I just installed MaraDNS on Redhat, just for testing, as an authoritative for ".whatever.com".   We also have our main DNS server configured to forward to my MaraDNS server for the ".whatever.com".

After initial setup I had 2 entries in the db.whatever.com:

fakewava04.whatever.com.        192.168.aaa.bb ~
fakewava.whatever.com.         192.168.aaa.bb ~

Both had the same IP, as I intended to fix that later.

However, now, after I change the 2nd entry, i.e. to:

fakewava04.whatever.com.        192.168.aaa.bb ~
fakewava.whatever.com.         192.168.ccc.dd ~

and bounce the maradns (and even bounced the entire machine), the fakewava.whatever.com is still resolving to the original IP, "192.168.aaa.bb".

I've tested by using nslookup and ping on both Redhat and Windows machines and on the latter, I have done "ipconfig /flushdns", but still the IP address for that fakewava.whatever.com does not change.

Do you have any idea what might be causing this problem?

Thanks,
Jim

**Comment by samboy** [comment]
MaraDNS correctly reloads zone files when restarted. MaraDNS will *not* dynamically reload a zone file; only a restart will change Mara’s zone data.

This is not a bug with MaraDNS but elsewhere in the resolution process, probably with another caching nameserver that is running. I also suggest using `dig` (or `askmara`) instead of `nslookup` to resolve names against the DNS server.

This is not a MaraDNS bug. Please use the [MaraDNS support forum](https://github.com/samboy/MaraDNS/discussions/87) if one continues to have issues: https://github.com/samboy/MaraDNS/discussions/87

**Comment by samboy** [comment]
Issue locked to avoid getting in to a flame war over support boundaries; I once had to delete a Github ticket when the guy started calling me names when I told him “no support in tickets”. Don’t take this personally: This is just my policy.
